name: geo_leaf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  file_picker: ^10.3.8
  maplibre_gl: ^0.25.0
  maptiler_flutter: ^0.1.0
  webview_flutter: ^4.13.1
  uuid: ^4.5.2
  flutter_svg: ^2.2.3
  camera: ^0.11.3
  cross_file_image: ^1.1.0
  geolocator: ^14.0.2
  loading_animation_widget: ^1.3.0
  tflite_flutter: ^0.12.1
  flutter_pytorch_lite: ^0.1.0+3
  path_provider: ^2.1.5
  maplibre_gl_web: ^0.25.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
    - assets/images/splash/
    - assets/images/
    - assets/images/icons/
    - assets/models/
